### ISSUE TITLE
Disable cache for test, or the ability to clear it in async modes

### ISSUE THREAD

**Issue by reneweteling** [whitfin/cachex#241] opened 2020-03-02 15:12 UTC
When using async tests with a shared Postgres connection, clearing a cache key in the test code does not clear the cache key in the server-side.

If you would inspect the cache in the test, it will be empty but when you inspect the key on the app side it isn't. 

I would like to disable the cachex for the test, or clear the cache key in the setup block only as described the the `Cachex.reset(:organisations)` does not work.

This is only the case for Async tests.

I've read https://github.com/whitfin/cachex/issues/213 i think the same issue applies here, only the question was not relayed properly.

Thanks!

**Comment by whitfin** [comment] 2020-08-13 00:07
Yes, this is the same question as the other thread. I read it again and thought my final response seemed a little harsh (not quite the word I want to use), but then I read it once again and I believe my response is actually the same.

Logically, the only way this can be an issue is if you have two tests running at the same time, both operating on the same cache key. In this scenario, the flaw lies in your test code. The `Cachex.reset/1` function already does what you are asking for; and yes it does work, because it's what I use in the library tests themselves (it's why this function exists). The root cause of your issue is that you have one test clearing your key, whilst the other test is putting it back. 

I'm not sure if this issue is asking for changes, but there is no way to stop this happening than to either:

* Use a different key in each test
* Run your tests sequentially (non-async)

This isn't something that can be "fixed" on the side of Cachex, because the logic issue is inside your test setup. The same concept applies to your question about disabling the cache for your tests; I'm not the person starting the cache - it's in your code somewhere. In the place that is done, you can check for the `Mix` environment and disable the cache accordingly. 

Let me know if this makes sense; I'm going to close this in the meantime!

**Closed by whitfin** 2020-08-13 00:07 UTC

**Comment by iamvery** [comment] 2023-08-11 15:02
> Use a different key in each test

Do you have a recommendation or idea for how to synchronize test-specific cache keys in apps? I would probably be helpful to the community to write up some docs about this problem along with recommendations for addressing it. It can be hard to identify esp. for newcomers to concurrency and who may not have considered the "global" implications of a cache store.
