### ISSUE TITLE
Question regarding Supervisor.Spec

### ISSUE THREAD

**Issue by micahrye** [whitfin/cachex#200] opened 2018-12-04 19:58 UTC
I was reading [issue 148](https://github.com/whitfin/cachex/issues/148) and I was wondering if/when  this project might be updated to use the new child specifications  (Elixir 1.5+)? 

In issue 148 @whitfin mentions what I assume is to refactor closer to the Supervisor.Spec being removed from the Elixir library, i.e. Elixir 2.0+. 

I recall a talk by José that Elixir would be a long time before that happens. This is good, as Supervisor.Spec and worker/3 will continue to work. 

This is more of a question if that refactor is in the roadmap, or if this is a desired refactor for others to do? 

... Forgot to add thanks for the cool project.

**Comment by whitfin** [comment] 2018-12-04 20:07
Hey @micahrye!

You're right that I tried this a whole ago. I basically gave up for the reasons you said; it's a long time away before this even matters and it was a pain to support for backwards compatibility in Cachex (which supports back to v1.2). I decided to wait until Elixir v2.0 comes out, which is likely when Cachex will break a whole bunch of stuff and raise the supported Elixir versions.

Having said that, I did some work in building [child-spec-compat](https://github.com/whitfin/child-spec-compat) which was supposed to be a way to compile down to the correct implementation based on the version of Elixir being used to compile. Although this library worked, I gave up trying to include it in Cachex itself because I found the standard library documentation very vague and didn't really understand the _point_ of the changes. 

If you'd like to migrate over in a backwards compatible way, then I'm all for merging! I just personally got a little frustrated the first couple of times I tried to go through with it. The linked library should be enough for the definitions - my issue was simply that I didn't understand exactly what the changes to stdlib were trying to push as the best way to define trees (I still don't).

I'm happy to work with you on this thread, or give it another shot myself, if you feel this is something we should do!

**Comment by alexcastano** [comment] 2019-07-09 09:42
An important consideration is that some people are new in Elixir and they studied only the new way. The doc just says:

```elixir
Supervisor.start_link(
  [ worker(Cachex, [ :my_cache, [] ]) ]
)
```

It is possible they don't know what `worker` function is. In my case, I didn't remember how the old way worked and I was a little bit frustrated until I got it :) And to import `Supervisor.Spec` which is deprecated is a little bit awkward; not a bit deal anyway.

**Comment by ourway** [comment] 2019-07-21 07:35
For those who waste their time searching for a simple answer:
Add this line to your supervisor children:

```elixir
{Cachex, :your_cache_name}
```

**Comment by Cohen-Carlisle** [comment] 2019-10-29 22:26
In addition to the syntax @ourway shared, if you want to provide cache-wide configuration/defaults, you can use a [child specification map](https://hexdocs.pm/elixir/Supervisor.html#module-child-specification), like below:
```elixir
import Cachex.Spec, only: [expiration: 1]
# define your child like so
%{
  id: :my_auth_cache,
  start: {Cachex, :start_link, [:my_auth, [expiration: expiration(default: 60_000)]]}
}
```

**Comment by NobbZ** [comment] 2020-01-15 14:03
> I decided to wait until Elixir v2.0 comes out

As I have understood Jóse, this will probably never happen.

Have you considered doing a major bump of `cachex`?

**Comment by whitfin** [comment] 2020-01-15 16:16
> Have you considered doing a major bump of cachex?

Is this not just a documentation issue? Is the issue talking about what Cachex uses internally, or how people start their caches? If the former, nobody really has to care. If the latter, there is no code change.

**Comment by NobbZ** [comment] 2020-01-15 21:48
The problem is, that you can not properly pass options using the convinient tuple syntax.

You either have to use the deprecated `Supervisor.Spec` macros, or alternatively write out the child-spec-map by hand, which can get tedious.

**Comment by benwilson512** [comment] 2020-01-26 00:00
Seconding @NobbZ, the documentation points people to use functions that are no longer automatically available within a supervisor, and cannot be used along side the new style tuples. Everyone's supervision trees are using the new style tuples since that's what mix / phoenix generates, and it makes starting Cachex confusing for beginners who then have to tackle writing out a child spec for it by hand.

**Comment by nickjj** [comment] 2020-01-26 00:27
Yep, instead of just the `+1`, I wanted to chime in with a bit of context. As a beginner, it took around 30 minutes of Googling, not being able to find an answer, finding a few blog posts using the "old" style and eventually getting help on IRC from Ben to begin using Cachex.

It would be a very welcome addition to have 2 examples in the docs. One for the basic case and one with configuration defaults. Both upvoted examples in this thread would be a great starting point.

**Comment by whitfin** [comment] 2020-02-12 16:38
Hey all, only just had time to circle around to this. I'm a little unclear what people are asking for... if this is documentation related, is it covered by https://github.com/whitfin/cachex/pull/237 and any changes we make there? I'm a little confused as @NobbZ seems to suggest that we need to change something in the lib itself, but I'm unsure as to what?

**Comment by Cohen-Carlisle** [comment] 2020-02-12 16:57
I think #237 will have it covered in that it documents a non-deprecated syntax to configure supervisors. Another option [documented here](https://hexdocs.pm/elixir/Supervisor.html#module-child_spec-1) is to define `Cachex.child_spec/1` to create the child specification map for the user, although it already seems to be defined, seemingly for a different purpose.

**Comment by NobbZ** [comment] 2020-02-12 17:57
The default `child_spec/1` as generated by `GenServer, is not capable to deal with `start_link/x when x != 1`, as it passes the second argument from the tuple as an argument to `start_link/1`, where the code generated by the old `worker` macros used an `apply` like mechanism to "adjust" number of arguments according to elements in the list.

If you really want to keep the current interface, you could create add a `child_spec/1` to your modules, that re-enables old way dispatching.

```
def child_spec(args) when is_list(args) do
  %{
    … # default stuff for GenServers
    start: {__MODULE__, :start_link, args} # do not wrap `args` in a list here!
  }
end
```

This is not well thought through, but may be used as an entrypoint.

**Comment by josevalim** [comment] 2020-02-27 09:54
The best option in this case is to change Cachex to receive all arguments as options.

Something like this:

```elixir
# For backwards compat
def start_link(name) when is_atom(name) do
  start_link(name: name)
end

def start_link(opts) when is_list(opts) do
  name = Keyword.fetch!(opts, :name)
  GenServer.start_link(..., opts, name: name)
end

# For backwards compat
def start_link(name, opts) do
  start_link([name: name] ++ opts)
end
```

Now you can use it as:

    {Cachex, name: :foo}
    {Cachex, name: :bar, expiration: expiration(default: 60_000)}

This is exactly what Elixir's Registry did.

To understand why the `worker`/`supervisor` API was problematic, we can take a look at what Cachex is doing:

```elixir
Supervisor.start_link(
  [ worker(Cachex, [:my_cache, []]) ]
)
```

However, if we look at Cachex' supervision tree, **the Cachex process is not a worker**, but a **supervisor**. The correct would be:

```elixir
Supervisor.start_link(
  [supervisor(Cachex, [:my_cache, []])]
)
```

Maybe it was a worker at some point but now it no longer is. When this transition from worker to supervisor happened, it made the previous usage wrong. This means some observability tools are not showing the whole tree and it also means cachex shutdown times in its inner supervsion tree are not being respected either. The new child spec API puts all definition at the hand of Cachex itself, instead of leaving them up to the user, which as we seen above, it is error-prone. Don't sweat about it though, Ecto also did this mistake for quite a long time. :)

**Comment by whitfin** [comment] 2020-03-10 16:33
@josevalim if it's exactly what the Registry did, it's clearly good enough for me :D I'll get around to this in a few days hopefully (or if anyone wants to PR, feel free!). Thanks for the explanation too - you're correct that it used to be a worker (long, long ago).

**Comment by whitfin** [comment] 2020-08-12 22:55
Hey everyone! Sorry it took forever (fairly distracted with current situations) but I've updated the signatures based on the advice from José above, and everything looks good. I updated the documentation too, so it should be more familiar. Please let me know if anything is encouraging a bad pattern; I haven't written much Elixir since the spec changes so I want to make sure I'm not portraying anything incorrectly.

I tested the changes with a few dependent packages from Hex and I'm pretty sure everything is fine in terms of backwards compatibility too, so should be good! I'm going to close this, but please do re-open if anything needs improvement. Sorry again for the delay!

**Closed by whitfin** 2020-08-12 22:55 UTC
Labels: question
