### ISSUE TITLE
Load disk dump on initialization

### ISSUE THREAD

**Issue by rottgoth** [whitfin/cachex#194] opened 2018-07-26 20:31 UTC
I have a GenServer that is in charge of calling `Cachex.start_link` and sends itself a message to load the cache dump from disk after initialization. 

It also calls a function that creates a backup on disk every X minutes and on terminate. The file seems to be created correctly.

```
defmodule MyCache.Server do
  use GenServer

  def init([name, opts]) do
    {:ok, pid} = Cachex.start_link(name, cache_opts)
    Process.send_after(self(), :load_cache_backup, 0)
    schedule_cache_backup()
    { :ok, {name, pid} }
  end

  def handle_info(:load_cache_backup, {name, pid} = state) do
    location = Path.join(System.cwd, "priv/cache_backup")
    Cachex.load(name, location)
    {:noreply, state}
  end

  def handle_info(:create_cache_backup, {name, _pid} = state) do
    location = Path.join(System.cwd, "priv/cache_backup")
    Cachex.dump(name, location)
    schedule_cache_backup() # Reschedule once more
    {:noreply, state}
  end

  defp schedule_cache_backup do
    Process.send_after(self(), :create_cache_backup, @backup_interval)
  end
end
```

The server runs fine and initializes the Cachex process correctly. But the problem is that when it should load the backup, it always returns `{:error, :unreachable_file}` although I was able to verify that the file is always there with content. I've started a iex session and creating the dump, then loading it successfully in the same location, I've compared the file's content with the version I'm trying to load on initialization and it is the same. 

I'm starting to think that this is related somehow to the version or process that created the dump, it may not the same that is trying to load it. 

Could that be a bug with `Cachex` way to loading the backup, maybe assuming something is there that isn't? or do you have any thoughts on what I could be doing wrong?

Thanks,

**Comment by whitfin** [comment] 2018-07-26 20:36
@rottgoth are you making the dump with the same version of OTP as what you're trying to load it with?

**Comment by rottgoth** [comment] 2018-07-26 20:44
@whitfin yeah, it is the same OTP version `Erlang/OTP 20 [erts-9.3.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]`. I'm just restarting my server, basically, I made the GenServer to ensure I don't lose the cache if the process dies

**Comment by whitfin** [comment] 2018-07-26 21:13
@rottgoth so you're saying that it works fine from iex, but a running application isn't working properly? That seems odd; I can take a look - do you want to create an example app that I can run with the code above to test it out? Just so we're working from the same thing.

**Comment by rottgoth** [comment] 2018-07-26 22:09
@whitfin very interestingly, I was debugging the issue further and seems like once I start a new iex session, the error still showing when trying to load the dump on initialization, but running this code borrowed from https://github.com/whitfin/cachex/blob/master/lib/cachex/disk.ex#L30 if I do something like `path |> File.read! |> :erlang.binary_to_term([ :safe ])` it throws `exception error: bad argument`, but if I run it like this: `path |> File.read! |> :erlang.binary_to_term` it works and calling it a second time with `[:safe]` seems to work fine.

Then I went ahead and created a sample app for you to test: https://github.com/rottgoth/cachex_sample 
It still logs the `{:error, :unreachable_file}` on initialization which seems to be consistent, but then a manual attempt worked fine (log in the README) which also errors in my other app.

In the sample app, the data I'm storing is too simple and small. Which makes me think the problem could also be related to the type of data I'm trying to store, but I'm not sure.

Here are some questions that I came up with to maybe find out what the issues could be, Is it ok to store any struct data in the cache? Is it recommended to encode into binary your data before creating the dump and decoding it after loading it? Could this be caused maybe if the app defining the structs hasn't loaded yet?

Thanks for the help!

**Comment by whitfin** [comment] 2018-07-26 22:15
Well, I'd think that your struct definitions must exist if your app has loaded enough to load the dump?

**Comment by rottgoth** [comment] 2018-07-26 22:18
Yeah, probably, I'm just trying to brainstorm any possible causes for the issue, I'm still learning elixir. Were you able to reproduce the issue on initialization?

**Comment by whitfin** [comment] 2018-07-26 22:20
@rottgoth unfortunately I haven't got a chance to test yet (replying to this thread from the office). I'll take a look as soon as I get a moment though! Appreciate the time taken to create the reproduction case.

**Comment by florinpatrascu** [comment] 2018-07-26 22:22
I don’t believe this is a cachex issue. Most probably you’re saving atoms to disk, and when you first try to initialize them from the cache saved to the disk, the :safe option will trigger the protection against creating them indirectly. That’s what I believe it is. Try using strings, for a test?! HTH

**Comment by florinpatrascu** [comment] 2018-07-26 23:54
Hi @rottgoth - I am glad it helped! Re best practice: I’d say the best practice is to stay safe and avoid additional data for transformation effort where is not required. Nothing wrong with using strings, especially for data coming from external sources - in fact it is recommend to do so. You’ll se similar warnings in other libraries as well I.e. Poison and so on. This is because atoms cannot be garbage collected, hence the extra care we should take around producing them indirectly. 

I can’t talk for what cachex could do in this respect, except that it is doing an awesome e job already for just being offered to us :) But no I don’t think a library should take that decision (of asserting what is safe and what is not) instead of the developer himself?! But that’s my humble opinion. Do you have any restrictions for using strings, in this code of yours?

**Comment by florinpatrascu** [comment] 2018-07-27 00:05
Also, for initializing the cache, when your app is initializing, I’d recommend looking at the [Cache warming](https://github.com/whitfin/cachex/tree/master/docs/features/cache-warming) support.

My other 0.02CAD
:)

**Comment by whitfin** [comment] 2018-07-27 00:31
@rottgoth since your issue is resolved, are you ok if I close this? Good learning for the next time someone hits the same issue :)

**Comment by rottgoth** [comment] 2018-07-27 00:52
@whitfin Yeah, I think it's ok to close it! :)

**Closed** 2018-07-27 00:53 UTC
Labels: discuss, question
