### ISSUE TITLE
Cachex.incr/3 hangs after calling several hundred times

### ISSUE THREAD

**Issue by ntrepid8** [whitfin/cachex#120] opened 2017-09-22 22:00 UTC
I'm not sure exactly how to describe the issue I'm having other than to say that `Cachex.incr/3` hangs after being called several hundred times. I tried some work-arounds like running it inside a `Cachex.execute/3` block but it didn't seem to make any difference.

I was never able to reproduce the hang without calling the function a "lot" so I'm not really sure what could be causing it but it feels like it's hitting some sort of deadlock. Possibly I'm not using it as intended?

Eventually I switched to using `Cachex.get_and_update/4` and simply did the addition in the callback. Using this function I was able to process much larger data sets without ever seeing a problem.

Is this something anyone else has seen? If it's helpful it can be reproduced with the following test case code:

```
  test "reproduce_cachex_hang" do
    keys_count = 5_000
    iterations = 2_000
    worker_count = 2

    # start cache
    Cachex.start_link(:my_test_cache, [])

    # generate keys
    keys =
      Enum.map(1..keys_count, fn(_index) ->
        :crypto.strong_rand_bytes(76) |> Base.encode64()
      end)

    Logger.debug("start tasks")
    tasks =
      Enum.map(1..worker_count, fn(_index) ->
        Task.async(fn ->
          # increment keys in cache
          Enum.map(1..iterations, fn(index) ->
            # get key/val
            key = Enum.take_random(keys, 1) |> Enum.at(0)
            val = :crypto.rand_uniform(1, 1_000)

            # increment option 1 (hangs at 5_000 keys, 2_000 interations, 2 workers)
            opts = [
              amount: val,
              initial: 0,
            ]
            Cachex.incr(:my_test_cache, key, opts)

            # # increment option 2 (succeeds at 5_000 keys, 10_000 interations, 2 workers)
            # Cachex.get_and_update(:my_test_cache, key,
            #   fn(existing_val) ->
            #     existing_val + val
            #   end,
            #   fallback: fn(_missing_key) -> 0 end)
          end)
        end)
      end)

    # await the results
    results =
      Task.yield_many(tasks, 30_000)
      |> Enum.map(fn {task, res} ->
        # Shutdown the tasks that did not reply nor exit
        Logger.debug("res=#{inspect res}")
        assert is_nil(res) == false
        res
      end)

    # print results
    Logger.debug("start results stream")
    cache_data = Cachex.stream!(:my_test_cache) |> Enum.to_list()
    Logger.debug("cache_data=#{inspect cache_data, pretty: true}")
  end
```

Something else that's strange is that even though the `Task.yield_many` should timeout after 30 seconds (it does timeout with `get_and_update` and more iterations) but with `incr` it never does. Everything just stops.

Any ideas? Am I using this function incorrectly?

**Comment by whitfin** [comment] 2017-09-22 22:36
@ntrepid8 Aloha, thank you for the report.

This seems like incredibly unlikely behaviour, but I'm going to take a shot at reproducing using the above... it feels like maybe the issue is stemming from all of that `Task` usage. Have you reproduced it without `Task` involved?

Also, for reference, which Elixir/OTP versions are you using?

**Comment by ntrepid8** [comment] 2017-09-22 23:12
I'm running Elixir 1.4, Erlang 18.2, Cachex ~2.0

In my production code I had a poolboy worker pool where each worker was doing a big map/reduce (essentially) and them loading the results into the Cachex cache. I wrote the test case with the Task worker to see if I could reproduce the behavior outside the context of any of my own code.

I suppose it could be an interaction that only happens when multiple processes are attempting to run an `incr` at the same time, but is that something that should happen? If so, should there be some sort of warning in the docs?

Thanks for the quick rely :)

**Comment by whitfin** [comment] 2017-09-22 23:15
@ntrepid8 ok, let me get that setup and try it out and get back to you. I believe it's an issue with the async nature of your code, rather than the Cachex interaction specifically.

`incr` is atomic and is backed by components in Erlang; it's probably not hanging. I'll try reproduce and see if I can narrow down your issue.

**Comment by whitfin** [comment] 2017-09-22 23:58
@ntrepid8 can you please try and reproduce on the latest OTP? It appears this is only reproducible on 18.2 for me. If I bump beyond 18.x, everything appears to be fine. 

It appears to be an issue with OTP as BEAM itself is hanging, not the Cachex calls (which would just hang that single process). Please let me know if updating to another OTP version fixes this for you so I can close the issue.

**Comment by ntrepid8** [comment] 2017-09-25 15:16
Ok, I'll try on a newer OTP and post when I have results.

**Comment by whitfin** [comment] 2017-10-13 23:33
I'm going to close this for now, but if @ntrepid8 has any additional info on later OTP versions, feel free to reopen.

**Closed by whitfin** 2017-10-13 23:33 UTC
Labels: discuss
