### ISSUE TITLE
Received `:nodedown` during local operation

### ISSUE THREAD

**Issue by scohen** [whitfin/cachex#207] opened 2019-01-13 18:23 UTC
I was integrating Cachex into our application and was also using your [local cluster](https://github.com/whitfin/local-cluster) library to ease testing and was quite surprised when I received a `nodedown` despite my cache operating in local mode. 

What's going on is when my app boots, it initializes a cache, which binds the current node (`nonode@nohost`) name into its internal state. Then when localcluster starts, it changes the node name to `master@127.0.0.1`. Then when any one of the `@keyed_actions` is run, [this line](https://github.com/whitfin/cachex/blob/master/lib/cachex/router.ex#L59) will fail to match, and cachex will use the remote configuration. 

I can submit a PR, but I don't quite know what you're going for; I think making `nodes` something like an empty list, `:local` or `nil` as a default would work better but I'm assuming there's a reason that it is the way it is. 

If one of the above solutions works for you, just say so and I'll push a PR.

**Comment by scohen** [comment] 2019-01-13 18:43
To be honest, I couldn't figure out where to file this bug -- either here or in local cluster. 

Local cluster unconditionally changes the node name from what it was before to `master@127.0.0.1`, so no matter what I do aside from starting the node with the name `master@...` there will be a conflict between what the name is bound to in cachex and what local cluster sets it to.

Also, it would be nice to not have to start local cluster for all my tests as it takes seconds to start, which will triple the amount of time it takes our tests to run.

Aside from the above, there's an ergonomics issue -- it's quite confusing to get a `nodedown` when you've not specified distributed operation.

**Comment by whitfin** [comment] 2019-01-13 18:55
@scohen doesn't really matter, because I'm not sure it's a bug of either - if we decide to change something specific we can file another issue!

> Local cluster unconditionally changes the node name from what it was before to master@127.0.0.1, so no matter what I do aside from starting the node with the name master@... there will be a conflict between what the name is bound to in cachex and what local cluster sets it to.

The issue you're having in general is that you're not following the paradigms set out by local-cluster. When using local-cluster, your test code is totally separate from your app instances. In your case, it would be better to start X nodes in a cluster, and start your cache on each nodes and test it remotely (i.e. RPC). Otherwise I'm not sure why you need local-cluster at all?

> Also, it would be nice to not have to start local cluster for all my tests as it takes seconds to start, which will triple the amount of time it takes our tests to run.

You can start it in your `test_helper.exs` before you start `ExUnit`, and it'll be alive the whole time - you can start multiple clusters without having to re-start it. I haven't tested this yet, but a helper file can look just like this:

```
:ok = LocalCluster.start()
ExUnit.start()
:ok = LocalCluster.stop()
```

That should (in theory) start it once and change your node name before any of your tests run, fixing your issue and without slowing your tests.

> Aside from the above, there's an ergonomics issue -- it's quite confusing to get a nodedown when you've not specified distributed operation.

I agree, but at the same time it's definitely an edge case.

**Comment by scohen** [comment] 2019-01-13 19:19
> The issue you're having in general is that you're not following the paradigms set out by local-cluster. 

Maybe I'm not (though I don't see where I mucked up, perhaps the documentation could be made more explicit); but the problem is that the sequence of events is:

 1. My app boots, setting its node name. This node name is locked into Cachex's configuration
 2. ExUnit starts starting localcluster, which changes the current node name (and if I've already started a node, it will fail, given the current with block implementation)
 3. calls to Cachex fail with nodedown.

To be clear, my intention isn't to test Cachex here, I'd like to test other distributed stuff and Cachex is failing on the current node in tests unrelated to the LocalCluster tests.

> When using local-cluster, your test code is totally separate from your app instances.

I don't think it's totally separate, as it changes the name of the current node. I think a totally separate paradigm would look like this:

```elixir
:ok = LocalCluster.start()
master = LocalCluster.master()
[node1, node2] = LocalCluster.start_nodes(2, "node")

:rpc.call(master, ModuleUnderTest, :setter, [a, b])
assert a == :rpc.call(node1, ModuleUnderTest, :getter, [a])
```
where all calls to the cluster have to be over `rpc`.  

I'm starting to think the problem is actually LocalCluster. You're right about how node names aren't supposed to change, but that's literally what LocalCluster does right off the bat. Mnesia also has problems with it.

**Comment by whitfin** [comment] 2019-01-13 20:36
> I'm starting to think the problem is actually LocalCluster. 

Sure, feel free to move it.

> I don't see where I mucked up, perhaps the documentation could be made more explicit.

It's hard, because I can't see code, but I guess another way to say it; why are you calling anything on the `ExUnit` node if you've started a cluster? Why are you using a cluster if you're testing Cachex on the local node rather than the cluster? If the issue is tests clashing with each other, put all your cluster tests in one file with a setup/teardown to stop/start local-cluster.

> I don't think it's totally separate, as it changes the name of the current node.

The point is that you should be running tests on the started cluster; not on the current node. You should be calling Cachex on one of those worker nodes via RPC - the master is not in the worker cluster.

> You're right about how node names aren't supposed to change, but that's literally what LocalCluster does right off the bat.

Yes, because `nonode@nohost` is the default and that's not applicable in a distributed environment - so it has to change the node name. No way around that.

**Comment by scohen** [comment] 2019-01-14 00:52
>  why are you calling anything on the ExUnit node if you've started a cluster?

Because I'm running a suite of tests and some of them run after the tests that make use of LocalCluster.
However, code is clearer, let's look at some. 
Say I have the following two tests:

```elixir
# distro_test.exs
defmodule MyTest do
  use ExUnit.Case

  test "something with a required cluster" do
    :ok = LocalCluster.start()

    nodes = LocalCluster.start_nodes("my-cluster", 3)
   [node1, node2, node3] = nodes

    assert Node.ping(node1) == :pong
   end
end
```
```elixir
# model_test.exs
defmodule DataModelCaching do 
  use ExUnit.Case 

  test "ensure models are cached on query" do 
   assert {:ok, false} == Cachex.exists?(:model_cache, "foo")
   {:ok, model} = Model.create("foo")
   assert {:ok, ^model} = Cachex.get(:model_cache, "foo")
  end
end
```
After `distro_test.exs` runs, unless I stop LocalCluster, my local node is now poisoned with respect to Cachex; its name no longer matches what Cachex has locked in during app start. Subsequent tests that exercise functionality that uses Cachex will now fail --even if they have no dependency on distribution. 

`model_test.exs` will fail on the call to `Cachex.exists?` with a nodedown error. The only way around this is to start and stop LocalCluster node for tests that make use of it (and incur a three second penalty for doing so) and not run them concurrently with other tests that make use of Cachex, LocalCluster or mnesia. 

Fairly large caveats for a library like LocalCluster (and Cachex) that at least warrant documentation. 

>  so it has to change the node name. No way around that

Not exactly; it could also gracefully handle the `{:error, {:already_started, _}}` error that `net_kernel` emits and use the name it's been given.

**Comment by whitfin** [comment] 2019-01-14 05:55
> Because I'm running a suite of tests and some of them run after the tests that make use of LocalCluster.

Ok, got it! That's what was unclear to me - the fact it's a "knock-on" effect makes sense. Originally I thought you were starting a cluster and then testing Cachex on the current node in the same test, and got a little confused as to why 😅. I've been thinking about the changing landscape in the past, but didn't realise how easy it is to cause library issues (I guess because it never occurred to me that your application tree starts first).

> Fairly large caveats for a library like LocalCluster (and Cachex) that at least warrant documentation.

In terms of Cachex, I don't think it requires any "fixing" as it's quite an edge case due to the root issue being that the node name changes at runtime. As this seems like it would only ever be a test/dev flow, I'm going to close this issue without changes - unless you disagree with this assessment! That being said, I do agree that there are some changes required in `local-cluster` itself. Rather than fork out another issue on that repo, I'd like to quickly discuss my quick plans here (as the context is right above):

First of all I'm going to update the documentation in the `local-cluster` README to include starting the server once in `test_helper.exs`. This eliminates the problem, rather than working something specific for Cachex (I'm almost certain other libraries exist with similar circumstances). It also makes the test environment much more "valid", rather than having things like the state of the node changing mid-way through test flows (and potentially causing races).

> Not exactly; it could also gracefully handle the {:error, {:already_started, _}} error that net_kernel emits and use the name it's been given.

Yeah, you're not wrong about this - it was actually in the original code but removed before release. I recall issues with the certain types of node name you needed to pass in order for things to run smoothly; rather than detail all of the rules to users, I went with the common case that nobody is passing a node name and assumed that a node would not already be started.

That being said, if you think it's worth changing, I'm definitely not against going back to ignoring it! in this case I change it, I would simply let any future errors bubble up from the OTP layer (I want to keep the surface area of the library itself small).

I think the documentation change to tweak how people interact with the library will be probably the best solution we can come up with, unless you have any other ideas. Do you think these changes are sufficient?

**Comment by scohen** [comment] 2019-01-14 17:12
I agree; I don't think the fix is in cachex any more --though I will admit being flummoxed when I passed `local: true` to my calls and it not changing things, and the `nodedown` error tuple was both confusing and wrapped incorrectly in an exception that failed to to_string it (resulting in another exception deep in Cachex that ExUnit didn't print out well). Perhaps handling the `nodedown` tuple in cachex and providing a more detailed error message would help? Agreed it's edge case-y, but our job is often to handle these extreme edge cases and file down their edges for our users.

The minimum viable fix of improving documentation in `LocalCluster` will work provided that someone: 
  
  1. Starts ExUnit without starting their app (requires aliasing `test` in mix.exs)
  2. In test_helper.exs one must:
    a. Start LocalCluster
    b. Start their app via `Application.ensure_all_started`
    c. Start ExUnit

That seems like a lot of work to foist on the developer, but it's your library and I can understand biasing it towards simplicity. As a somewhat simple fix, Perhaps you could introduce present node name detection, or allow the node name to be set? If you want me to play around with this, I'll be more than happy to do it. LocalCluster is pretty much exactly what I wrote at my last company and we found it indispensable when testing distribution. `:slave_node` is really useful, but quite low-level as are the incantations required to boot the average Elixir application. Having a library do this for us is a really big win, and I was quite happy to see LocalCluster.

> I recall issues with the certain types of node name you needed to pass

Yeah, that's probably due to the long names / short names divide in erlang. If you want to enforce long names, you could detect the `@` symbol in the atom.

**Comment by whitfin** [comment] 2019-01-14 20:07
> The minimum viable fix of improving documentation in LocalCluster will work 

Yes, I have a draft of that documentation already, as well as examples.

> That seems like a lot of work to foist on the developer
...
>  As a somewhat simple fix, perhaps you could introduce present node name detection, or allow the node name to be set?

I'm planning on doing both of these things (mentioned above). I think the two approaches cater to different types of developers; the documentation case gives developers an easy copy/paste from the README which is done once. When you consider that `LocalCluster.start/1` is already scattered around their tests, I actually think this an improvement.

I think the fact you find this simpler comes from you being clearly already familiar, having worked on similar code. However, providing a name at startup requires learning the CLI options how, and also understanding exactly what a valid name is. Although this can be beneficial in the long term, I just want to highlight that this is no simpler than the `test_helper.exs` changes for users who don't already have that knowledge. I'm not entirely sure if you can even provide aliases for this, which makes it a permanent change to your CLI over `mix test` (of course I might be mistaken about this though). 

> If you want me to play around with this, I'll be more than happy to do it.

I appreciate the offer, but I already have most of it locally! I didn't want to push it without hearing back from you to make sure you felt it was an appropriate way to go!

My current plan is to push my documentation changes, which don't require any code change. I'm also going to quietly allow already started nodes in a patch release (as it's actually a bug that we don't already have this). 

I'm not sure of the value of allowing the node name to be set, as it wouldn't help the original issue you reported (because you obviously couldn't set `nonode@nohost`). I think it sufficient to allow the node name to be set and kept via the CLI. If you have a use case where this option would help, please LMK. I'm not against it in principle, I just don't see a use case where it provides any value.

**Comment by scohen** [comment] 2019-01-14 21:23
> 'm planning on doing both of these things (mentioned above). 

I must have misread your comment; that sounds great.

> I appreciate the offer, but I already have most of it locally! 

I don't want to be one of those people who just expect you to fix everything in your project for me. Open source in that world is just a burden; But since you have it running locally, then I'm glad to try it out.

> I'm not sure of the value of allowing the node name to be set, as it wouldn't help the original issue you reported (because you obviously couldn't set nonode@nohost).
 
The value comes from when people are starting ExUnit with distribution up and running. 

Ping me when you've pushed something; I'd love to take a look!

**Comment by whitfin** [comment] 2019-01-14 21:31
@scohen the latest master of `local-cluster` should now just accept your own distributed `ExUnit` setup (I think). If anything fails, just ping me a repro case and I can take another look.

I also updated the docs, LMK if you think they're clear enough!

**Closed** 2019-01-14 21:46 UTC

**Comment by scohen** [comment] 2019-01-15 21:16
I'll take a look.

**Comment by scohen** [comment] 2019-01-18 01:41
I took a look, things work great with the instructions provided, and they incur zero latency. Now I need to figure out how to get ecto to cooperate with tests on the remote node, but that's well out of scope. 

Than you, can can we get a LocalCluster release?

**Comment by whitfin** [comment] 2019-01-18 02:20
@scohen yep! I was just waiting for your confirmation. I'll push a patch release out right now.

**Comment by scohen** [comment] 2019-01-18 03:00
Thanks so much!
